return {
	{
		action = "vehiclefly|vfly",
		description = "Makes you fly in a vehicle",
		args = {
			kind = "number",
			name = "vehicle fly speed",
			optional = true
		}
	},
	{
		action = "vehicleflyspeed|vflyspeed",
		description = "Set vehicle fly speed",
		args = {
			kind = "number",
			name = "vehicle fly speed"
		}
	},
	{
		action = "unvehiclefly|unvfly",
		description = "Disables vehicle fly"
	}
}