--[[
	infinite yield (remake)
	
	ramake made by: real_redz (redz hub team)
	original version by: edges
	
	format: (MM/DD/YYYY)
		started coding at: 06/06/2026
		coding break from: 06/15/2026 at: 10/07/2026
			During that period, I lost the most recent version of the source code, 'v0.0.5'.
			So I decided to skip from version 'v0.0.4' to 'v0.0.6'.
		release at: not released
]]

return require("./src/core"):boot()