return {
	{
		action = "xray",
		description = "Makes all parts in workspace transparent"
	},
	{
		action = "unxray|noxray",
		description = "Restores transparency to all parts in workspace"
	},
	{
		action = "loopxray",
		description = "Makes all parts in workspace transparent but looped"
	},
	{
		action = "unloopxray",
		description = "Unloops xray"
	},
	{
		action = "togglexray",
		description = "Toggles xray"
	}
}