return {
	require("./discord"),        -- done
	require("./guiscale"),       -- done
	require("./console"),        -- done
	require("./scripts"),        -- done
	require("./serverinfo"),
	require("./gameinfo"),
	require("./creatorid"),      -- done
	require("./rejoin"),         -- done
	require("./autorejoin"),     -- done
	require("./serverhop"),
	require("./selfkick"),       -- done
	require("./gameteleport"),   -- done
	require("./antiafk"),        -- done
	require("./datalimit"),      -- done
	require("./replicationlag"), -- done
	require("./setfpscap"),      -- done
	require("./showprompts"),    -- done
	require("./togglegui"),      -- done
	require("./showguis"),       -- done
	-- require("./guidelete"),   -- maybe later
	require("./hideiy"),
	require("./keepiy"),
	require("./removeads"),      -- done
	require("./saveinstance"),   -- maybe later
	require("./clearerror"),
	require("./antigameplaypaused"),
	require("./clientantikick"),
	require("./clientantiteleport"),
	require("./allowrejoin"),
	require("./cancelteleport"),      -- done
	require("./volume"),              -- done
	require("./antilag"),             -- done
	require("./screen"),              -- done
	require("./notify"),              -- done
	require("./lastcommand"),         -- done
	require("./notifyping"),          -- done
	require("./render"),              -- done
	require("./use2022materials"),    -- done
	require("./alignmentkeys"),       -- done
	require("./ctrllock"),            -- done
	require("./exit"),                -- done
	-- require("./removecommand"),
	-- require("./breakloops")
	require("./notifyjobid"),
	require("./copyids"),
	require("./enable"),
	require("./nilinstances"),
	require("./mousesens"),
	require("./friends"),
	require("./respawn"),
	require("./debug"),
	require("./team"),
	require("./handlekill"),
	require("./autoclick"),
	require("./watch"),
	require("./keybinds"),
	require("./promptrig")
}
