return {
	DisplayName = "Dark",
	
	Font = {
		Normal = Enum.Font.BuilderSans,
		Medium = Enum.Font.BuilderSansMedium,
		Bold = Enum.Font.BuilderSansBold,
		ExtraBold = Enum.Font.BuilderSansExtraBold,
		MonoSpace = Enum.Font.RobotoMono
	},
	Colors = {
		Background = Color3.fromRGB(19, 19, 19),
		Primary = Color3.fromRGB(88, 101, 242),
		OnPrimary = Color3.fromRGB(61, 67, 135),
		Stroke = Color3.fromRGB(45, 45, 45),
		
		Error = Color3.fromRGB(255, 102, 102),
		Icons = Color3.fromRGB(232, 233, 235),
		
		ScrollBar = {
			Thumb = Color3.fromRGB(60, 60, 60),
			Arrow = Color3.fromRGB(232, 233, 235),
			Background = Color3.fromRGB(26, 26, 26)
		},
		Buttons = {
			Holding = Color3.fromRGB(42, 42, 42),
			Default = Color3.fromRGB(34, 34, 34)
		},
		Border = {
			Holding = Color3.fromRGB(60, 60, 60),
			Default = Color3.fromRGB(38, 38, 38),
		},
		Text = {
			Default = Color3.fromRGB(255, 255, 255),
			Dark = Color3.fromRGB(200, 200, 200),
			Darker = Color3.fromRGB(175, 175, 175),
		},
		Slider = {
			SliderBar = Color3.fromRGB(1, 76, 105),
			SliderNumber = Color3.fromRGB(232, 233, 235),
		},
	}
}