return {
	createService     = require("./createService"),
	specialProps      = require("./createService/specialProps"),
	
	connectionService = require("./connectionService"),
	fetchService      = require("./fetchService"),
	localPlayer       = require("./localPlayer"),
	messageService    = require("./messageService"),
	playerService     = require("./playerService"),
	rbxServices       = require("./rbxServices"),
	tweenService      = require("./tweenService"),
}