return {
	["bindsandplugins"] =         "rbxassetid://5147695474",
	["close"] =                   "rbxassetid://5054663650",
	["editaliases"] =             "rbxassetid://5147488658",
	["editkeybinds"] =            "rbxassetid://129697930",
	["edittheme"] =               "rbxassetid://4911962991",
	["editwaypoints"] =           "rbxassetid://5147488592",
	["imgstudiopluginlogo"] =     "rbxassetid://4113050383",
	["logo"] =                    "rbxassetid://1352543873",
	["minimize"] =                "rbxassetid://2406617031",
	["pin"] =                     "rbxassetid://6234691350",
	["reference"] =               "rbxassetid://3523243755",
	["settings"] =                "rbxassetid://1204397029",
}